;-------------------------------------------------------------------------------------------------
;SUBROUTINE: SUB_FUNCTIONNAME_ADDRESS
;INPUT:
;POST CONDITION:
;RETURN VALUE:
;-------------------------------------------------------------------------------------------------
xADDRESS

;BACK UP ALL MODIFIED REGISTERS EXCEPT THE RETURN REGISTER
ST R0, BACK_UP_R0_ADDRESS
ST R1, BACK_UP_R1_ADDRESS
ST R2, BACK_UP_R2_ADDRESS
ST R3, BACK_UP_R3_ADDRESS
ST R4, BACK_UP_R4_ADDRESS
ST R5, BACK_UP_R5_ADDRESS
ST R6, BACK_UP_R6_ADDRESS
ST R7, BACK_UP_R7_ADDRESS

;ALGORITHIM
;RESTORE REGISTERS
LD R0, BACK_UP_R0_ADDRESS
LD R1, BACK_UP_R1_ADDRESS
LD R2, BACK_UP_R2_ADDRESS
LD R3, BACK_UP_R3_ADDRESS
LD R4, BACK_UP_R4_ADDRESS
LD R5, BACK_UP_R5_ADDRESS
LD R6, BACK_UP_R6_ADDRESS
LD R7, BACK_UP_R7_ADDRESS

;RETURN
RET

;DATA BLOCK FOR SUB_FUNCTION_NAME
BACK_UP_R0_ADDRESS    .BLKW #1
BACK_UP_R1_ADDRESS    .BLKW #1
BACK_UP_R2_ADDRESS    .BLKW #1
BACK_UP_R3_ADDRESS    .BLKW #1
BACK_UP_R4_ADDRESS    .BLKW #1
BACK_UP_R5_ADDRESS    .BLKW #1
BACK_UP_R6_ADDRESS    .BLKW #1
BACK_UP_R7_ADDRESS    .BLKW #1

ENTER    .FILL #10

;===================================================
;HOW TO WORK WITH THE TEMPLATE
;1. COPY/PASTE THE REMPLATE IN THE CODE, WHERE U WANT TO HAVE THE FUCNTIONS
;2. REPLACE ALL INSTANCES OF ADDRESS WITH THE ADDRESS OF THE FUCNTION (EG; 3200, 3400, 3600)
;3. FILL OUT THE HEADER
;4. FOR ALL REGISTERS IN "RETURN VALUE" DELETE THE FORM STORE & RESTORE SECTIONS
;   (EG; IF R6 AND R1 ARE RETURN VALUES, DELETE THESE LINES:
;    ST R6, BACK_UP_R6_ADDRESS
;    ST R1, BACK_UP_R1_ADDRESS
;    LD R6, BACK_UP_R6_ADDRESS
;    LD R1, BACK_UP_R1_ADDRESS
;   )
